Some changes
pspdev/psptoolchain pull request #142
Opened 2021-01-05 21:39 UTC by wally4000

1. Removed need for patches, toolchain now depends on the local git repo objects for fetching (Correct branches at time). This will make it easier to maintain and quicker for future deployments / patches via CI.
2. Removed the git script component as git was new at the time, now it's common knowledge and can be scripted to a one liner. Better for people who know how git works and enables the ability to use --depth=1 to speed up fetching of objects.

I have tested this and it works fine

2021-01-05 22:19 UTC, sharkwouter requested changes
Hey Wally, thanks for working on this, I think this is very needed. I'm a little bit confused about some of the changes here, though. Especially the use of git clone over clone_git_repo. Is that function broken? Might be worth fixing.

The commented out code can also be removed. We have git for that :)

2021-01-05 22:19 UTC, sharkwouter commented on scripts/001-binutils.sh
> +git clone https://github.com/pspdev/binutils --depth=1
You may want to use the clone_git_repo function here

2021-01-05 22:19 UTC, sharkwouter commented on scripts/001-binutils.sh
> +# patch -p1 < ../../patches/binutils-"$BINUTILS_VERSION"-PSP.patch
Removing comments would be welcome

2021-01-05 22:19 UTC, sharkwouter commented on scripts/006-pspsdk-stage2.sh
> - clone_git_repo github.com pspdev pspsdk
This should probably stay, even if the directory probably already exists. Otherwise we may see some breakage later.

2021-01-05 22:19 UTC, sharkwouter commented on scripts/013-profile.sh
> + set -e
The changes to this file don't really add anything

2021-01-05 22:19 UTC, sharkwouter commented on scripts/005-gcc-stage2.sh
> +# git clone https://github.com/pspdev/gcc -b gcc-9.3.0-psp --depth=1
Both clones are commented out here

2021-01-05 22:25 UTC, sharkwouter commented
This currently fails to build for me on ``scripts/001-binutils.sh``. Here is the log: https://gist.github.com/sharkwouter/c940d71c17b903814f23cdd3dca2cf5b

2021-06-08 05:06 UTC, wally4000 commented
Not applicable anymore, closing

2021-06-08 05:06 UTC, closed without merging